name: __projectName__
description: An Aqueduct web server application.
version: 0.0.1
#homepage: https://www.example.com
#author: __author__ <email@example.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  aqueduct: ^2.0.0

dev_dependencies:
  test: ^0.12.0
